### ISSUE TITLE
Any risk of unique or quest ingestible hand placed by mods?

### ISSUE THREAD

**Issue by Soukmancer** [Coyote21/FoodRemover#5]
More of a question than an issue, but is there a risk that mod place unique or quest ingestibles could be removed with this? If I remember scarcity would occasionally have this problem

**Comment by Coyote21** [comment]
Sorry been so long I needed to review the code to remember how it worked.

Anyway, by default, un-configured, straight out of the box, yes it could remove quest ingestibles added by mods, it looks for the string "Food" in the item ID so if the mod author used the string "Food" in the item's id then it could be removed.

However, you can use the skipPlugins.json file to stop this. Just add the mod's plugin filename into the skipPlugins.json file and FoodRemover will ignore all items placed by that mod (more accurately it will skip any cells/locations modified by that mod, but same diff).

Also, if you know the location of the hand placed item, you can also add the location ID to the skipLocation.json file for similar results.

Both options are listed under "Settings" in the ReadMe.md file.
