### ISSUE TITLE
Patcher somehow transforms CC Myrwatch cell into a formless void.

### ISSUE THREAD

**Issue by ghost** [Coyote21/FoodRemover#6]
If you allow this patcher to run on _Myrwatch_, a Creation Club Mage Tower mod included with _Anniversary Edition_,  much of the cell's architecture is removed such that the PC falls into a void upon entering. For modlists including _AE,_  this cell must be manually reverted each time which is often forgotten. Please make an exception in this patcher to exclude the cell with Editor ID `ccEEJSSE002MageTowerMain` located in Block 7, Sub-Block 0, FormID `FE01383B`.

**Comment by Coyote21** [comment]
Any/all the cells in any mod can already be excluded using the skipLocations.json and/or skipPlugin.json settings files supplied.
Please review README file for instructions and let me know if you need more clarification.

**Comment by ghost** [comment]
Apologies, don't know how I missed that. Not enough sleep I guess!

**Comment by Coyote21** [comment]
No probs, I've experienced the same many (many, many, ....) times myself.
